propose:
  description: >
    Stai proponendo la mozione: {motion}.
    Elabora un'argomentazione chiara a favore della mozione.
    Sii molto convincente.
  expected_output: >
    La tua argomentazione chiara a favore della mozione, esposta in modo conciso.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    Ti opponi alla mozione: {motion}.
    Formula un argomento chiaro contro la mozione.
    Sii molto convincente.
  expected_output: >
    La tua chiara argomentazione contro la mozione, esposta in modo conciso.
  agent: debater
  output_file: output/oppose.md
  
decide:
  description: >
    Esamina le argomentazioni presentate dai dibattenti e decidi quale parte sia più convincente.
  expected_output: >
   La tua decisione su quale delle due parti sia più convincente, e perché.
  agent: judge
  output_file: output/decide.md